# Site settings
title: "matthiaslischka.at"
email: 
description: "Just another developer blog"
baseurl: ""
url: "https://matthiaslischka.github.io/"
title_description: "Professional nerd. Thoughts and findings.<br />Lorem Ipsum. Just do git. Foo Bar. 'or 1=1."
title_image: "https://www.gravatar.com/avatar/00cb52564e474a4c98f7c6bc8eac4d05?s=500&d=mm"
google_analytics: "UA-37678138-1"
disqus_account: matthiaslischka
github_repository: https://github.com/matthiaslischka/matthiaslischka.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: matthiaslischka
github_username: matthiaslischka
instagram_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link: https://www.xing.com/profile/Matthias_Lischka
facebook_link:

# Footer
footer_left: "I <i class=\"fa fa-heart\"></i> u."
footer_right: "&lt;/&gt; on <a href=\"https://github.com/matthiaslischka/matthiaslischka.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

plugins:
  - jekyll-sitemap
